refactor: fix implicit 'any' type
Error log.

```sh
axios-mock-server $ node node_modules/.bin/tsc

__tests__/index.spec.ts:18:11 - error TS7034: Variable 'router' implicitly has type 'any[]' in some locations where its type cannot be determined.

18     const router = []
             ~~~~~~

__tests__/index.spec.ts:20:44 - error TS7005: Variable 'router' implicitly has an 'any[]' type.

20     db = (await mockServer(client, models, router)).db
                                              ~~~~~~

src/AsyncNedb.ts:25:66 - error TS7006: Parameter 'err' implicitly has an 'any' type.

25       return new Promise((resolve, reject) => super.find(query, (err, documents) => {
                                                                    ~~~

src/AsyncNedb.ts:25:71 - error TS7006: Parameter 'documents' implicitly has an 'any' type.

25       return new Promise((resolve, reject) => super.find(query, (err, documents) => {
                                                                         ~~~~~~~~~

src/index.ts:80:10 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'MockAdapter'.
  No index signature with a parameter of type 'string' was found on type 'MockAdapter'.

80         (mock[`on${method[0].toUpperCase()}${method.slice(1)}`] as typeof mock.onAny)(regPath).reply(async ({ url, baseURL, data = '{}' }) =>
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 5 errors.
```